version: '3.8'
services:
  knowledgehub-postgres-db:
    image: postgres:15-alpine
    container_name: knowledgehub_postgres
    environment:
      POSTGRES_DB: knowledgehub_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  knowledgehub-app:
    build: .
    container_name: knowledgehub_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/knowledgehub_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
#      JWT_SECRET: YourSuperSecretKeyForJWT
    depends_on:
      - knowledgehub-postgres-db
    restart: on-failure

  knowledgehub- elasticsearch:
    image: elasticsearch:7.17.10
    container_name: knowledgehub_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

volumes:
  postgres_data:
  elasticsearch_data: